import type {Metadata} from "next"
import localFont from "next/font/local"
import "./globals.css"
import Header from "@/components/header/header"
import React from "react"
import {Toaster} from "@/components/ui/toaster"

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
})
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
})

export const metadata: Metadata = {
    title: "Клевер",
    description: "Generated by create next app",
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <script
                src="https://yastatic.net/s3/passport-sdk/autofill/v1/sdk-suggest-with-polyfills-latest.js"></script>
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
        >
        <Header/>
        <div style={{marginTop: "80px"}}></div>

        {children}
        <Toaster/>
        </body>
        </html>
    )
}
